ARG version
FROM almalinux:${version:-8}
#RUN cat/etc/*release
ARG course=docker
ARG LEARNER=vikram
ENV Duration=20hrs
RUN echo "Course is: ${course},LEARNER is : ${LEARNER},Duration is : ${Duration}"
CMD [ "sleep","60" ]
