FROM almalinux:9
ADD https://raw.githubusercontent.com/daws-78s/notes/main/session-01.txt /tmp/session-01.txt
# add instruction will also extract after detecting.. example tar files
ADD sample.tar / tmp/  
CMD [ "sleep","60" ]